# Generated by Django 5.2.7 on 2026-04-22 19:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., 'Fuel', 'Wrench')",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#004D40",
                        help_text="Hex color code for UI",
                        max_length=7,
                    ),
                ),
                ("is_income", models.BooleanField(default=False)),
                (
                    "is_fixed",
                    models.BooleanField(
                        default=False,
                        help_text="Fixed expense (rent, insurance) vs variable",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DriverProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_goal",
                    models.DecimalField(
                        decimal_places=2,
                        default=400.0,
                        help_text="Target daily net profit in local currency",
                        max_digits=10,
                    ),
                ),
                (
                    "safety_net_target",
                    models.DecimalField(
                        decimal_places=2,
                        default=5000.0,
                        help_text="Emergency fund target amount",
                        max_digits=10,
                    ),
                ),
                (
                    "safety_net_current",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current emergency fund balance",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GHS", "Ghana Cedi"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("NGN", "Nigerian Naira"),
                            ("KES", "Kenyan Shilling"),
                        ],
                        default="GHS",
                        max_length=3,
                    ),
                ),
                ("language", models.CharField(default="en", max_length=5)),
                ("timezone", models.CharField(default="Africa/Accra", max_length=50)),
                ("is_shift_active", models.BooleanField(default=False)),
                ("shift_start_time", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique device identifier for sync",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("SUCCESS", "Success"),
                            ("ALERT", "Alert"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "action_label",
                    models.CharField(
                        blank=True,
                        help_text="Button text (e.g., 'View Report')",
                        max_length=50,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, help_text="Deep link to screen", max_length=200
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                (
                    "is_persistent",
                    models.BooleanField(
                        default=False, help_text="Should user manually dismiss?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Model name (Transaction, Vault, etc.)", max_length=50
                    ),
                ),
                (
                    "instance_id",
                    models.CharField(
                        help_text="Local ID of the record", max_length=100
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(help_text="Serialized record data to sync")),
                ("retry_count", models.IntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        help_text="Which device performed sync", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("CONFLICT", "Conflict Detected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_count",
                    models.IntegerField(
                        default=0, help_text="Number of transactions synced"
                    ),
                ),
                ("bytes_uploaded", models.BigIntegerField(default=0)),
                ("bytes_downloaded", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "server_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Server time of record"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Vault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "vault_type",
                    models.CharField(
                        choices=[
                            ("Emergency Net", "Emergency Net"),
                            ("Vehicle Upgrade", "Vehicle Upgrade"),
                            ("School Fees", "School Fees"),
                            ("Business Growth", "Business Growth"),
                            ("Custom", "Custom"),
                        ],
                        default="Custom",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("icon", models.CharField(default="ShieldCheck", max_length=50)),
                ("color", models.CharField(default="#004D40", max_length=7)),
                (
                    "allocation_percent",
                    models.IntegerField(
                        default=0, help_text="Auto-allocation % from income"
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(
                        default=False, help_text="Is this the primary safety net?"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_emergency", "name"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(default="Toyota", max_length=50)),
                ("model", models.CharField(default="Corolla", max_length=50)),
                ("year", models.IntegerField(default=2020)),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                (
                    "current_odometer",
                    models.IntegerField(default=0, help_text="Current km reading"),
                ),
                (
                    "last_service_odometer",
                    models.IntegerField(default=0, help_text="Km at last service"),
                ),
                (
                    "service_interval_km",
                    models.IntegerField(
                        default=5000, help_text="Service interval in km"
                    ),
                ),
                (
                    "fuel_efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=12.5,
                        help_text="Litres per 100km or ₵/km",
                        max_digits=5,
                    ),
                ),
                (
                    "last_fuel_quantity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "last_fuel_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("roadworthy_expiry", models.DateField(blank=True, null=True)),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "health_score",
                    models.IntegerField(
                        default=85,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance_fund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maintenance_fund_target",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        help_text="e.g., Oil Change, Brake Pad Replacement",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "odometer_reading",
                    models.IntegerField(help_text="Odometer at time of service"),
                ),
                ("service_date", models.DateField()),
                (
                    "receipt_image",
                    models.URLField(
                        blank=True, help_text="Link to uploaded receipt", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="finance.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date"],
            },
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("Operating Costs", "Operating Costs"),
                            ("Business Growth", "Business Growth"),
                            ("Safety Net", "Safety Net"),
                            ("Personal/Home", "Personal/Home"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("color", models.CharField(default="#004D40", max_length=7)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("driver", "label")},
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budget limit for this period",
                        max_digits=12,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("weekly", "Weekly"),
                            ("quarterly", "Quarterly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("driver", "category", "period")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("MOMO", "Mobile Money"),
                            ("BANK", "Bank Transfer"),
                            ("CARD", "Card Payment"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        help_text="Purpose or description (e.g., 'Morning fuel')",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "odometer_reading",
                    models.IntegerField(
                        blank=True,
                        help_text="Vehicle km at time of transaction (for fuel/repair)",
                        null=True,
                    ),
                ),
                (
                    "synced",
                    models.BooleanField(
                        default=False, help_text="Has this been uploaded to cloud?"
                    ),
                ),
                (
                    "local_id",
                    models.CharField(
                        blank=True,
                        help_text="Temporary ID for offline edits",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finance.category",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["driver", "created_at"],
                        name="finance_tra_driver__746aca_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "category"],
                        name="finance_tra_transac_fd2805_idx",
                    ),
                ],
            },
        ),
    ]
